services:
    PoP\ComponentModel\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\ComponentModel\DirectiveResolvers\:
        resource: '../src/DirectiveResolvers/*'
        public: true
