parameters:
    version: '0.1.0'

services:
    _defaults:
        bind:
            PoP\Translation\Contracts\TranslationAPIInterface: '@translation_api'
            PoP\Hooks\Contracts\HooksAPIInterface: '@hooks_api'
            PoP\ComponentModel\Info\ApplicationInfoInterface: '@application_info'
            PoP\ComponentModel\Managers\ModulePathManagerInterface: '@module_path_manager'
            PoP\ComponentModel\ModelInstance\ModelInstanceInterface: '@model_instance'
            PoP\ComponentModel\Schema\ErrorMessageStoreInterface: '@error_message_store'
            PoP\ComponentModel\Schema\TypeCastingExecuterInterface: '@type_casting_executer'

    memory_cache_item_pool:
        class: \Symfony\Component\Cache\Adapter\ArrayAdapter
        public: true

    persistent_cache_item_pool:
        class: \Symfony\Component\Cache\Adapter\FilesystemAdapter
        public: true

    memory_cache:
        class: \PoP\ComponentModel\Cache\Cache
        public: true
        arguments:
            $cacheItemPool: '@memory_cache_item_pool'

    model_instance:
        class: \PoP\ComponentModel\ModelInstance\ModelInstance
        public: true

    application_info:
        class: \PoP\ComponentModel\Info\ApplicationInfo
        public: true
        arguments:
            $version: '%version%'

    module_filter_manager:
        class: '\PoP\ComponentModel\Managers\ModuleFilterManager'
        public: true
        arguments:
            $modulePathHelpers: '@module_path_helpers'

    module_path_manager:
        class: \PoP\ComponentModel\Managers\ModulePathManager
        public: true

    module_path_helpers:
        class: \PoP\ComponentModel\Managers\ModulePathHelpers
        public: true

    instance_manager:
        class: \PoP\ComponentModel\Managers\InstanceManager
        public: true

    error_message_store:
        class: \PoP\ComponentModel\Schema\ErrorMessageStore
        public: true

    field_query_interpreter:
        class: \PoP\ComponentModel\Schema\FieldQueryInterpreter
        public: true

    type_casting_executer:
        class: \PoP\ComponentModel\Schema\TypeCastingExecuter
        public: true

    attachable_extension_manager:
        class: \PoP\ComponentModel\AttachableExtensions\AttachableExtensionManager
        public: true

    PoP\ComponentModel\FieldValueResolvers\:
        resource: '../src/FieldValueResolvers/*'
        public: true

    PoP\ComponentModel\DirectiveResolvers\:
        resource: '../src/DirectiveResolvers/*'
        public: true
