parameters:
    version: '0.1.0'

services:
    _defaults:
        bind:
            PoP\Translation\TranslationAPIInterface: '@translation_api'
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\ComponentModel\Info\ApplicationInfoInterface: '@application_info'
            PoP\ComponentModel\ModulePath\ModulePathManagerInterface: '@module_path_manager'
            PoP\ComponentModel\ModelInstance\ModelInstanceInterface: '@model_instance'
            PoP\ComponentModel\Schema\FeedbackMessageStoreInterface: '@feedback_message_store'
            PoP\ComponentModel\Schema\TypeCastingExecuterInterface: '@type_casting_executer'
            PoP\QueryParsing\QueryParserInterface: '@query_parser'

    memory_cache_item_pool:
        class: \Symfony\Component\Cache\Adapter\ArrayAdapter
        public: true

    persistent_cache_item_pool:
        class: \Symfony\Component\Cache\Adapter\FilesystemAdapter
        public: true

    object_dictionary:
        class: \PoP\ComponentModel\Container\ObjectDictionary
        public: true

    engine:
        class: \PoP\ComponentModel\Engine\Engine
        public: true

    dataloading_engine:
        class: \PoP\ComponentModel\Engine\DataloadingEngine
        public: true

    memory_cache:
        class: \PoP\ComponentModel\Cache\Cache
        public: true
        arguments:
            $cacheItemPool: '@memory_cache_item_pool'

    model_instance:
        class: \PoP\ComponentModel\ModelInstance\ModelInstance
        public: true

    application_info:
        class: \PoP\ComponentModel\Info\ApplicationInfo
        public: true
        arguments:
            $version: '%version%'

    module_filter_manager:
        class: '\PoP\ComponentModel\ModuleFilters\ModuleFilterManager'
        public: true
        arguments:
            $modulePathHelpers: '@module_path_helpers'

    module_path_manager:
        class: \PoP\ComponentModel\ModulePath\ModulePathManager
        public: true

    data_structure_manager:
        class: \PoP\ComponentModel\DataStructure\DataStructureManager
        public: true

    module_path_helpers:
        class: \PoP\ComponentModel\ModulePath\ModulePathHelpers
        public: true

    instance_manager:
        class: \PoP\ComponentModel\Instances\InstanceManager
        public: true

    module_processor_manager:
        class: \PoP\ComponentModel\ModuleProcessors\ModuleProcessorManager
        public: true

    feedback_message_store:
        class: \PoP\ComponentModel\Schema\FeedbackMessageStore
        public: true

    field_query_interpreter:
        class: \PoP\ComponentModel\Schema\FieldQueryInterpreter
        public: true

    type_casting_executer:
        class: \PoP\ComponentModel\Schema\TypeCastingExecuter
        public: true

    schema_definition_service:
        class: \PoP\ComponentModel\Schema\SchemaDefinitionService
        public: true

    attachable_extension_manager:
        class: \PoP\ComponentModel\AttachableExtensions\AttachableExtensionManager
        public: true

    route_module_processor_manager:
        class: \PoP\ComponentModel\ModuleRouting\RouteModuleProcessorManager
        public: true

    PoP\ComponentModel\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\ComponentModel\DirectiveResolvers\:
        resource: '../src/DirectiveResolvers/*'
        public: true
